### ISSUE TITLE
Not working on Android 6.0.1

### ISSUE THREAD

**Issue by venkatarachakondadcmail** [capacitor-community/speech-recognition#59] opened 2023-02-24 01:29 UTC
**Describe the bug**
The application got deployed successfully into the android device but when we see the logs in inspect, it is not functioning as expected on Android 6.0.1, does this support the device, I have a demo on Monday.

**Comment by jcesarmobile** [comment] 2023-05-18 14:27
can you provide a sample app that reproduces the issue?
Does it only happen on Android 6?
Are you using `popup: true`? if so, it's a know issue already reported and I've just merged a PR that fixes the issue.

**Comment by jcesarmobile** [comment] 2023-06-09 07:40
closing since there was no response, the plugin was working fine for me, try latest version (5.0.0) as it included several fixes

**Closed by jcesarmobile** 2023-06-09 07:40 UTC
Labels: needs-reply
