### ISSUE TITLE
Ionic 5 + Capacitor 3 = white screen on Android

### ISSUE THREAD

**Issue by CedNet** [capacitor-community/speech-recognition#22] opened 2021-11-03 10:10 UTC
**Describe the bug**
White screen on start of app on Android. Not tested on iOS yet.

**To Reproduce**
I added the plugin to existing app.
Added the example code for pure testing.
Synced Android Studio and Gradle.
Added the plugin to MainActivity.

**Expected behavior**
App to start

**Screenshots**

**Additional context**
I see errors in the log that Storage is not available. 
Error row dumps that might be interesting.
```
- [ERROR:network_service_instance_impl.cc(179)] Failed to grant sandbox access to network context data for /data/user/0/*******/app_webview/Default with result 7: No such file or directory (2)
- Msg: ERROR Error: Uncaught (in promise): Error: "Storage" plugin is not implemented on android
- E/Capacitor/Console: File: http://localhost/main-es2015.0b2dd69512aa3b9132eb.js - Line 1 - Msg: Service worker registration failed with: TypeError: Failed to register a ServiceWorker for scope ('http://localhost/') with script ('http://localhost/ngsw-worker.js'): An unknown error occurred when fetching the script.
```

I'm willing to pay to get time with you to solve this.

The MainActivity file looks like this, no errors. Latest Android Studio and Gradle versions.

```
package *******;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import com.getcapacitor.community.speechrecognition.SpeechRecognition;

import java.util.ArrayList;

public class MainActivity extends BridgeActivity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Initializes the Bridge
        this.init(
                savedInstanceState,
                new ArrayList<Class<? extends Plugin>>() {

                    {
                        // Additional plugins you've installed go here
                        // Ex: add(TotallyAwesomePlugin.class);
                        add(SpeechRecognition.class);
                    }
                }
        );
    }

}
```

**Comment by mrbatista** [comment] 2021-11-04 11:17
Hi @CedNet. Create a repository with the minimal code to reproduce the issue.
Only relevant code.

**Comment by CedNet** [comment] 2021-11-04 12:51
@mrbatista i'll try to produce a failing repo. 

Another question. Does this plugin work as a Service while app is in the background? I need for people to be able to talk to the app while phone is in pocket, and they talk via a bluetooth device.

**Comment by jcesarmobile** [comment] 2023-02-03 16:49
I can't reproduce with latest version and the reporter never provided a sample app, so closing as can't be reproduced.

**Closed by jcesarmobile** 2023-02-03 16:49 UTC
